import './policyPage.scss';

const PolicyPage = () => {


    return (
        <div className="policy">
            Personal data processing policy
            <ul>
            <li>1. General provisions This personal data processing policy has been drawn up in accordance with the requirements of the Federal Law of 27.07.2006. No. 152-FZ "On Personal Data" (hereinafter referred to as the Law on Personal Data) and determines the procedure for processing personal data and measures to ensure the security of personal data taken by AIO LLC (hereinafter referred to as the Operator).</li>
            <li>1.1. The operator sets as its most important goal and condition for the implementation of its activities the observance of the rights and freedoms of a person and a citizen in the processing of his personal data, including the protection of the rights to privacy, personal and family secrets.</li>
            <li>1.2. This Operator's policy regarding the processing of personal data (hereinafter referred to as the Policy) applies to all information that the Operator can receive about visitors to the website <a href="https://aio.com">https://aio.com</a>"><a href="https://aio.com">https://aio.com</a>"><a href="https://aio.com">https://aio.com</a>"><a href="https://aio.com">https://aio.com</a>.</li>
            <li>2. Basic concepts used in the Policy</li>
            <li>2.1.  Automated processing of personal data - processing of personal data using computer technology.</li>
            <li>2.2.  Blocking of personal data is a temporary suspension of the processing of personal data (except when processing is necessary to clarify personal data).</li>
            <li>2.3.  Website - a set of graphic and information materials, as well as computer programs and databases that ensure their availability on the Internet at the network address <a href="https://aio.com">https://aio.com</a>.</li>
            <li>2.4.  Information system of personal data - a set of personal data contained in databases, and information technologies and technical means that ensure their processing.</li>
            <li>2.5.  Depersonalization of personal data - actions as a result of which it is impossible to determine, without the use of additional information, the ownership of personal data by a specific User or other subject of personal data.</li>
            <li>2.6.  Processing of personal data - any action (operation) or a set of actions (operations) performed with or without the use of automation tools with personal data, including collection, recording, systematization, accumulation, storage, clarification (updating, changing), extraction, use, transfer (distribution, provision, access), depersonalization, blocking, deletion, destruction of personal data.</li>
            <li>2.7.  Operator - a state body, municipal body, legal entity or individual, independently or jointly with other persons organizing and (or) carrying out the processing of personal data, as well as determining the purposes of processing personal data, the composition of personal data to be processed, the actions (operations) performed with personal data.</li>
            <li>2.8.  Personal data - any information relating directly or indirectly to a specific or identifiable User of the website <a href="https://aio.com">https://aio.com</a>"><a href="https://aio.com">https://aio.com</a>"><a href="https://aio.com">https://aio.com</a>"><a href="https://aio.com">https://aio.com</a>"><a href="https://aio.com">https://aio.com</a>"><a href="https://aio.com">https://aio.com</a>"><a href="https://aio.com">https://aio.com</a>"><a href="https://aio.com">https://aio.com</a>"><a href="https://aio.com">https://aio.com</a>"><a href="https://aio.com">https://aio.com</a>"><a href="https://aio.com">https://aio.com</a>.</li>
            <li>2.9.  Personal data permitted by the subject of personal data for dissemination - personal data, access to an unlimited number of persons to which is provided by the subject of personal data by giving consent to the processing of personal data permitted by the subject of personal data for distribution in the manner prescribed by the Law on Personal Data (hereinafter referred to as personal data). data allowed for distribution).</li>
            <li>2.10. User - any visitor to the website <a href="https://aio.com">https://aio.com</a>.</li>
            <li>2.11. Provision of personal data - actions aimed at disclosing personal data to a certain person or a certain circle of persons.</li>
            <li>2.12. Dissemination of personal data - any actions aimed at disclosing personal data to an indefinite circle of persons (transfer of personal data) or familiarizing with personal data of an unlimited number of persons, including the disclosure of personal data in the media, placement in information and telecommunication networks or providing access to personal data in any other way.</li>
            <li>2.13. Cross-border transfer of personal data is the transfer of personal data to the territory of a foreign state to an authority of a foreign state, a foreign individual or a foreign legal entity.</li>
            <li>2.14. Destruction of personal data - any actions as a result of which personal data are destroyed irretrievably with the impossibility of further restoration of the content of personal data in the information system of personal data and (or) material carriers of personal data are destroyed.</li>
            
           
            Basic rights and obligations of the Operator
            <li>3.1. The Operator has the right: - to receive reliable information and / or documents containing personal data from the subject of personal data; - in the event that the subject of personal data withdraws consent to the processing of personal data, the Operator has the right to continue processing personal data without the consent of the subject of personal data if there are grounds specified in the Law on Personal Data; - independently determine the composition and list of measures necessary and sufficient to ensure the fulfillment of the obligations provided for by the Law on Personal Data and the regulatory legal acts adopted in accordance with it, unless otherwise provided by the Law on Personal Data or other federal laws.</li>
            <li>3.2 . The operator is obliged: - to provide the subject of personal data, at his request, with information regarding the processing of his personal data; - to organize the processing of personal data in the manner established by the current legislation of the Russian Federation; - to respond to requests and requests from subjects of personal data and their legal representatives in accordance with the requirements of the Law on personal data; - report to the authorized body for the protection of the rights of subjects of personal data, at the request of this body, the necessary information within 30 days from the date of receipt of such a request; - publish or otherwise provide unrestricted access to this Policy regarding the processing of personal data;</li>
            - take legal, organizational and technical measures to protect personal data from unauthorized or accidental access to them, destruction, modification, blocking, copying, provision, distribution of personal data, as well as from other illegal actions in relation to personal data;
            - stop the transfer (distribution, provision, access) of personal data, stop processing and destroy personal data in the manner and cases provided for by the Law on Personal Data; - perform other duties provided for by the Law on Personal Data.
            <li>4. Basic rights and obligations of personal data subjects</li>
            <li>4.1. Subjects of personal data have the right to: - receive information regarding the processing of their personal data, with the exception of cases provided for by federal laws. The information is provided to the subject of personal data by the Operator in an accessible form, and it should not contain personal data related to other subjects of personal data, unless there are legal grounds for disclosing such personal data. The list of information and the procedure for obtaining it is established by the Law on Personal Data; - require the operator to clarify his personal data, block or destroy them if the personal data is incomplete, outdated, inaccurate, illegally obtained or not necessary for the stated purpose of processing, and also take measures provided for by law to protect their rights; - put forward a condition for prior consent when processing personal data in order to promote goods, works and services on the market; - withdraw consent to the processing of personal data; - appeal to the authorized body for the protection of the rights of personal data subjects or in court, illegal actions or inaction of the Operator in the processing of his personal data; - to exercise other rights provided for by the legislation of the Russian Federation.</li>
            <li>4.2. Subjects of personal data are obliged to: - provide the Operator with reliable data about themselves; - inform the Operator about the clarification (update, change) of their personal data.</li>
            <li>4.3. Persons who have provided the Operator with false information about themselves or information about another subject of personal data without the consent of the latter, are liable in accordance with the legislation of the Russian Federation.</li>
            <li>5. The Operator may process the following personal data of the User</li>
            <li>5.1. Surname, name, patronymic.</li>
            <li>5.2. Email address.</li>
            <li>5.3. Phone numbers.</li>
            <li>5.4. The site also collects and processes anonymous data about visitors (including " cookies ") using Internet statistics services (Yandex Metrika and Google Analytics and others).</li>
            <li>5.5. The above data further in the text of the Policy are united by the general concept of Personal data.</li>
            <li>5.6. Processing of special categories of personal data relating to race, nationality, political views, religious or philosophical beliefs, intimate life, is not carried out by the Operator.</li>
            <li>5.7. Processing of personal data permitted for distribution from among the special categories of personal data specified in Part 1 of Art. 10 of the Law on Personal Data is allowed if the prohibitions and conditions provided for in Art. 10.1 of the Personal Data Law.</li>
            <li>5.8. The User's consent to the processing of personal data permitted for distribution is issued separately from other consents to the processing of his personal data. At the same time, the conditions provided for, in particular, Art. 10.1 of the Personal Data Law. The requirements for the content of such consent are established by the authorized body for the protection of the rights of subjects of personal data.</li>
            <li>5.8.1 Consent to the processing of personal data permitted for distribution, the User provides the Operator directly.</li>
            <li>5.8.2 The Operator is obliged no later than three working days from the date of receipt of the specified consent The user to publish information on the conditions of processing, on the existence of prohibitions and conditions for the processing by an unlimited number of persons of personal data permitted for distribution.</li>
            <li>5.8.3 The transfer (distribution, provision, access) of personal data authorized by the subject of personal data for distribution must be terminated at any time at the request of the subject of personal data. This requirement should include the last name, first name, patronymic (if any), contact information (telephone number, e-mail address or postal address) of the subject of personal data, as well as a list of personal data, the processing of which is subject to termination. The personal data specified in this request can be processed only by the Operator to whom it was sent. data.</li>
            <li>6. Principles of personal data processing</li>
            <li>6.1. The processing of personal data is carried out on a legal and fair basis.</li>
            <li>6.2. The processing of personal data is limited to the achievement of specific, predetermined and legitimate purposes. It is not allowed to process personal data that is incompatible with the purposes of collecting personal data.</li>
            <li>6.3. It is not allowed to combine databases containing personal data, the processing of which is carried out for purposes incompatible with each other.</li>
            <li>6.4. Only personal data that meet the purposes of their processing are subject to processing.</li>
            <li>6.5. The content and scope of the processed personal data correspond to the stated purposes of processing. The redundancy of the processed personal data in relation to the stated purposes of their processing is not allowed.</li>
            <li>6.6. When processing personal data, the accuracy of personal data, their sufficiency, and, if necessary, relevance in relation to the purposes of processing personal data, is ensured. The operator takes the necessary measures and / or ensures their adoption to remove or clarify incomplete or inaccurate data.</li>
            <li>6.7. The storage of personal data is carried out in a form that allows determining the subject of personal data, no longer than required by the purposes of processing personal data, if the period for storing personal data is not established by federal law, an agreement to which the subject of personal data is a party, beneficiary or guarantor. The processed personal data is destroyed or depersonalized upon reaching the goals of processing or in case of loss of the need to achieve these goals, unless otherwise provided by federal law.</li>
            <li>7. Purposes of personal data processing</li>
            <li>7.1. The purpose of processing the User's personal data: - informing the User by sending emails; - providing the User with access to the services, information and / or materials contained on the website <a href="https://aio.com">https://aio.com</a>.</li>
            <li>7.2. The Operator also has the right to send notifications to the User about new products and services, special offers and various events. The User can always opt out of receiving informational messages by sending an email to the Operator at privacy@thismywebsite·com with the note "Opt out of notifications about new products and services and special offers".</li>
            <li>7.3. Anonymized data of Users, collected with the help of Internet statistics services, serve to collect information about the actions of Users on the site, improve the quality of the site and its content.</li>
            <li>8. Legal grounds for the processing of personal data</li>
            <li>8.1. The legal grounds for the processing of personal data by the Operator are: <span>- list the legal acts governing relations related to your activities, for example, if your activities are related to information technology, in particular the creation of websites, then here you can indicate the Federal Law "On Information, Information technologies and information protection" dated July 27, 2006 N 149-FZ;</span></li>
            - statutory documents of the Operator; - agreements concluded between the operator and the subject of personal data; - federal laws, other regulatory legal acts in the field of personal data protection; - Users' consent to the processing of their personal data, to the processing of personal data permitted for distribution.
            <li>8.2 . The Operator processes the User's personal data only if they are filled in and / or sent by the User independently through special forms located on the website <a href="https://aio.com">https://aio.com</a> or sent to the Operator by e-mail. By filling out the relevant forms and / or sending his personal data to the Operator, the User expresses his consent to this Policy.</li>
            <li>8.3. The Operator processes anonymized data about the User if it is allowed in the User's browser settings (the saving of " cookies " and the use of JavaScript technology is enabled).</li>
            <li>8.4. The subject of personal data independently decides on the provision of his personal data and gives consent freely, of his own free will and in his own interest.</li>
            <li>9. Conditions for the processing of personal data</li>
            <li>9.1. The processing of personal data is carried out with the consent of the subject of personal data to the processing of his personal data.</li>
            <li>9.2. The processing of personal data is necessary to achieve the goals stipulated by an international treaty of the Russian Federation or the law, to carry out the functions, powers and obligations assigned by the legislation of the Russian Federation to the operator.</li>
            <li>9.3. The processing of personal data is necessary for the administration of justice, the execution of a judicial act, an act of another body or official subject to execution in accordance with the legislation of the Russian Federation on enforcement proceedings.</li>
            <li>9.4. The processing of personal data is necessary for the performance of an agreement to which the subject of personal data is a party or beneficiary or guarantor, as well as to conclude an agreement on the initiative of the subject of personal data or an agreement under which the subject of personal data will be the beneficiary or guarantor.</li>
            <li>9.5. The processing of personal data is necessary to exercise the rights and legitimate interests of the operator or third parties, or to achieve socially significant goals, provided that the rights and freedoms of the subject of personal data are not violated. 9.6. The processing of personal data is carried out, access of an unlimited number of persons to which is provided by the subject of personal data or at his request (hereinafter referred to as publicly available personal data).</li>
            <li>9.7. Processing of personal data subject to publication or mandatory disclosure in accordance with federal law.</li>
            <li>10. The procedure for collecting, storing, transferring and other types of processing of personal data The security of personal data processed by the Operator is ensured by implementing the legal, organizational and technical measures necessary to fully comply with the requirements of the current legislation in the field of personal data protection.</li>
            <li>10.1. The Operator ensures the safety of personal data and takes all possible measures to exclude access to personal data of unauthorized persons.</li>
            <li>10.2. The User's personal data will never, under any circumstances, be transferred to third parties, except in cases related to the implementation of the current legislation or if the subject of personal data has given consent to the Operator to transfer data to a third party to fulfill obligations under a civil law contract.</li>
            <li>10.3 . In case of detection of inaccuracies in personal data, the User can update them independently by sending a notification to the Operator at the Operator's e-mail address privacy@thismywebsite com marked "Updating personal data".</li>
            <li>10.4. The term for the processing of personal data is determined by the achievement of the purposes for which the personal data were collected, unless a different period is provided for by the contract or applicable law. The User may at any time withdraw his consent to the processing of personal data by sending a notification to the Operator by e-mail at the Operator's email address privacy@ thismywebsite·com marked "Withdrawal of consent to the processing of personal data".</li>
            <li>10.5. All information that is collected by third-party services, including payment systems, means of communication and other service providers, is stored and processed by these persons (Operators) in accordance with their User Agreement and Privacy Policy. The subject of personal data and / or the User is obliged to independently familiarize themselves with the specified documents in a timely manner. The Operator is not responsible for the actions of third parties, including the service providers specified in this paragraph.</li>
            <li>10.6. The prohibitions established by the subject of personal data on the transfer (except for granting access), as well as on the processing or processing conditions (except for obtaining access) of personal data permitted for distribution, do not apply in cases of processing personal data in state, public and other public interests determined by law RF.</li>
            <li>10.7. The operator, when processing personal data, ensures the confidentiality of personal data.</li>
            <li>10.8. The operator stores personal data in a form that allows to determine the subject of personal data, no longer than required by the purposes of processing personal data, if the period for storing personal data is not established by federal law, an agreement to which the subject of personal data is a party, beneficiary or guarantor.</li>
            <li>10.9. The condition for terminating the processing of personal data may be the achievement of the purposes of processing personal data, the expiration of the consent of the subject of personal data or the withdrawal of consent by the subject of personal data, as well as the identification of unlawful processing of personal data.</li>
            <li>11. List of actions performed by the Operator with the received personal data</li>
            <li>11.1. The operator collects, records, systematizes, accumulates, stores, clarifies (updates, changes), extracts, uses, transfers (distributes, provides, accesses), depersonalizes, blocks, deletes and destroys personal data.</li>
            <li>11.2. The operator carries out automated processing of personal data with the receipt and / or transmission of the received information via information and telecommunication networks or without it.</li>
            <li>12. Cross-border transfer of personal data</li>
            <li>12.1. Before the start of the cross-border transfer of personal data, the operator is obliged to make sure that the foreign state, to whose territory it is planned to transfer personal data, provides reliable protection of the rights of subjects of personal data. 12.2. Cross-border transfer of personal data on the territory of foreign states that do not meet the above requirements can be carried out only if there is a written consent of the subject of personal data to the cross-border transfer of his personal data and / or execution of an agreement to which the subject of personal data is a party.</li>
            <li>13. Confidentiality of personal data The operator and other persons who have gained access to personal data are obliged not to disclose to third parties and not to distribute personal data without the consent of the subject of personal data, unless otherwise provided by federal law.</li>
            <li>14. Final provisions</li>
            <li>14.1. The User can receive any clarifications on questions of interest regarding the processing of his personal data by contacting the Operator via e-mail privacy@thismywebsite·com .</li>
            <li>14.2. This document will reflect any changes in the policy of processing personal data by the Operator. The policy is valid indefinitely until it is replaced by a new version.</li>
            <li>14.3. The current version of the Policy is freely available on the Internet at <a href="https://aio.com/policy">https://aio.com/policy</a>.</li>
            </ul>
        </div>
    )
}

export default PolicyPage;